version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: tienda_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tienda_online
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build: .
    container_name: tienda_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: tienda_online
    stdin_open: true
    tty: true
